# Generated by Django 4.0.4 on 2022-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
