# Generated by Django 4.0.4 on 2022-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_updateprofile_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='ProfilePic',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
