# Generated by Django 4.0.4 on 2022-08-27 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_updateprofile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='ProfilePic',
        ),
    ]
