# Generated by Django 4.0.4 on 2022-08-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_updateprofile_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='ProfilePic',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
