# Generated by Django 4.0.4 on 2022-08-27 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_updateprofile_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofile',
            old_name='username',
            new_name='user',
        ),
    ]
