# Generated by Django 4.0.4 on 2022-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_name_updateprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='skills',
            field=models.CharField(max_length=50),
        ),
    ]
