# Generated by Django 4.0.4 on 2022-08-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_updateprofile_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofile',
            old_name='username',
            new_name='name',
        ),
    ]
