# Generated by Django 4.0.4 on 2022-08-27 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_username_updateprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofile',
            old_name='name',
            new_name='username',
        ),
    ]
