# Generated by Django 4.0.4 on 2022-08-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_name_updateprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofile',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
